version: 0.2

phases:
  install:
    commands:
      # Yarn installation
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - sudo apt-get -y update
      - apt-get install -y yarn
      - yarn
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - yarn build
  post_build:
    commands:
      - yarn remove react react-dom react-scripts bulma
      - echo Build completed on `date`

artifacts:
  files:
    - build
    - package.json
    - bin
    - app.js
    - .elasticbeanstalk
    - .ebextensions